language: java

sudo: false

addons:
  hosts:
    - DB

services:
  - docker

install:
  - docker build -t database DB/.
  - docker run --rm -d -e MYSQL_ROOT_PASSWORD=example -p 33060:3306 database
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
  - mvn clean

script:
  - mvn test -Dtest=com.napier.DevOps4.AppTest