language: java

sudo: false

addons:
  hosts:
    - DB

services:
  - docker

install:
  - docker build -t database DB/.
  - docker run --rm -d -e MYSQL_ROOT_PASSWORD=example -p 33060:3306 database
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
  - mvn clean

jobs:
  include:
    - stage: unit tests

      jdk: oraclejdk11
      script: mvn test -Dtest=com.napier.DevOps4.AppTest
    - stage: integration tests
      jdk: oraclejdk11
      script: mvn test -Dtest=com.napier.DevOps4.AppIntegrationTest
    - stage: deploy

      jdk: oraclejdk11
      script:
        - mvn package -DskipTests=true -Dmaven.javadoc.skip=true
        - docker-compose up --abort-on-container-exit

stages:
  - unit tests
  - integration tests
  - name: deploy
    if: branch = master